name: Generate Anki Deck and Create Release

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install genanki

    - name: Run script to generate Anki deck
      id: generate_deck
      run: |
        python anki-gen.py
        ls *.apkg > apkg_filename.txt

    - name: Read generated file name
      id: read_filename
      run: echo "APKG_FILE=$(cat apkg_filename.txt)" >> $GITHUB_ENV

    - name: Upload Anki deck as artifact
      uses: actions/upload-artifact@v3
      with:
        name: anki-deck
        path: '*.apkg'

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: v1.0.0  # Change this to your desired tag
        release_name: Anki Deck Release
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.APKG_FILE }}
        asset_name: anki-deck.apkg  # This name can be anything you prefer
        asset_content_type: application/octet-stream
